// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExt9Vjato1pMUvkD9hKYDdkgJ8SstpQU',
    appId: '1:302661900941:web:e0d259af5a8999431e20c4',
    messagingSenderId: '302661900941',
    projectId: 'mooviez-49695',
    authDomain: 'mooviez-49695.firebaseapp.com',
    storageBucket: 'mooviez-49695.appspot.com',
    measurementId: 'G-P4414X3G9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZAqGoxjjWt5kuEdUoa_rK-IR97yCa9P0',
    appId: '1:302661900941:android:f57c07a94071563b1e20c4',
    messagingSenderId: '302661900941',
    projectId: 'mooviez-49695',
    storageBucket: 'mooviez-49695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoDa9chDW9LB9-aY-jrEUxPGnu3ZeWek',
    appId: '1:302661900941:ios:e46e84fb6e06ab1b1e20c4',
    messagingSenderId: '302661900941',
    projectId: 'mooviez-49695',
    storageBucket: 'mooviez-49695.appspot.com',
    iosClientId: '302661900941-gl1g1b3niavbuoppvpg8pucgti08ldd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpoDa9chDW9LB9-aY-jrEUxPGnu3ZeWek',
    appId: '1:302661900941:ios:e46e84fb6e06ab1b1e20c4',
    messagingSenderId: '302661900941',
    projectId: 'mooviez-49695',
    storageBucket: 'mooviez-49695.appspot.com',
    iosClientId: '302661900941-gl1g1b3niavbuoppvpg8pucgti08ldd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
